### ISSUE TITLE
Separate compiler engine and public macro APIs

### ISSUE THREAD

**Issue by olafurpg** [scalacenter/macros#18]
## Current design
In the current prototype, the public macro API is the same API that compiler engines implement.

An example subset of the core API.
```scala
// in Universe.scala
trait Universe extends Trees

// in trees/Trees.scala
trait Trees extends Abstracts with Companions with Extensions {
  self: Universe =>
  type Tree
  type Term <: Tree
  val Term: TermCompanion = new TermCompanion{}
  trait TermCompanion {
    def Name = abstracts.TermName
  }
}

// in trees/Abstracts.scala
trait Abstracts { self: Universe =>
  def abstracts: TreeAbstracts
  trait TreeAbstracts {
    def treePos(tree: Tree): Position
    def TermName: TermNameCompanion
  }
}

// in trees/Companions.scala
trait Companions { self: Universe =>
  def abstracts: TreeAbstracts
  trait TreeCompanions {
    trait TermNameCompanion {
      def apply(value: String): Term.Name
      def unapply(arg: Any): Option[String]
    }
  }
}

// in trees/Extensions.scala
trait Extensions { self: Universe =>
  implicit class XtensionTreesTree(tree: Tree) extends Prettyprinted {
    def pos: Position = abstracts.treePos(tree)
  }
}

// in macros/package.scala
package object scala.macros extends Universe {
  // universe is set by compiler before macro expansion
  private[macros] val universe = new ThreadLocal[scala.macros.Universe]
  private[macros] def abstracts = {
    if (universe.get == null) sys.error("this API can only be called in a macro expansion")
    universe.get.abstracts.asInstanceOf[Abstracts]
  }
}
```

What the compiler engine implements.

```scala
// in ScalacUniverse.scala
class ScalacUniverse(g: Global) extends Universe {
  type Tree = g.Tree
  type Term = g.Tree
  override val Term: TermCompanion.type = TermCompanion
  object TermCompanion extends TermCompanion {
    type Name = g.Ident
  }

  object abstracts extends TreeAbstracts {
    def treePos(tree: Tree) = tree.pos
    object TermName extends TermNameCompanion {
      def apply(value: String): Term.Name = g.Ident(value)
      def unapply(arg: Any): Option[String] = arg match {
        case g.Ident(value) => Some(value)
        case _ => None
      }
    }
  }
}
```

What macro authors write

```scala
// in MyMacro.scala
import scala.macros._
def myMacro(a: A): A = macro {
  a.pos // XtensionTreesTree.pos
  a match {
    case Term.Name(value) => // TermNameCompanion.unapply
      Term.Name(name) // TermNameCompanion.apply
  }
  ???
}
```

This design is good in that it
- requires only a single `import scala.macros._` for macro authors
- re-uses the same API parts for compiler engines and macro authors
- relies (only) on a single provably-safe cast in `macros/package.scala`

However, this design has several problems

- cyclic dependencies between source files. Example,
  - `TreeCompanions` depends on `Trees.Term.Name`
  - `Trees.Term.Name` depends on `TreeAbstracts.TermName`
  - `TreeAbstracts.TermName` depends on `TreeCompanions`
- public macro author APIs like `XtensionTreesTree.pos` are in the   scope of `ScalacUniverse`, making it easy to accidentally introduce   infinite recursion.
- Awkward code navigation for macro authors ("Jump to definition" in IDE).   Example, too inspect `Term.Name.apply`
  - `Term.Name` in MyMacro.scala opens trees/Trees.scala
  - `TermName` in trees/Trees.scala opens trees/Abstracts.scala
  - `TermNameCompanion` will open trees/Abstracts.scala
- unusual `Name.apply`/`Name.unapply` inference from `def Name: NameCompanion`.   I'm not aware of any Scala library that uses this design pattern.   IntelliJ shows red squiggly marks.

## New proposed design

Me and @liufengyun brainstormed for an alternative encoding with the core objective to *separate compiler engine API from public macro author API*. A prototype of this design can be seen here:
https://github.com/scalacenter/macros/commit/94d03572711f31746c0a80c868b8b5552ae0376c
```scala
// macros/Universe.scala
trait Universe {
  type Position
  type Tree
  def treePos(tree: Tree): Position
  type Term <: Tree
  type TermName <: Tree
  def termNameApply(value: String): TermName
  def termNameUnapply(arg: Any): Option[String]
}

// compiler engine: ScalacUniverse.scala
class ScalacUniverse(g: Global) extends Universe {
  type Position = g.Position
  type Tree = g.Position
  def treePos(tree: Tree): Position = tree.pos
  type Term = g.Position
  type TermName = g.Ident
  def termNameApply(value: String): TermName = g.Ident(value)
  def termNameUnapply(arg: Any): Option[String] = ???
}

// public macro API: macros/package.scala
package object macros {
  private[macros] val universeStore = new ThreadLocal[Universe]
  private[macros] def universe: Universe = {
    val result = universeStore.get
    if (result == null) sys.error("this API can only be called in a macro expansion")
    else result
  }
  type Position
  type Tree; implicit class XtensionTree(tree: Tree) {
    def pos: Position = universe.treePos(tree).asInstanceOf[Position]
  }
  type Term <: Tree
  object Term {
    type Name <: Term
    object Name {
      def apply(value: String): Term.Name =
        universe.termNameApply(value).asInstanceOf[Term.Name]
      def unapply(arg: Any): Option[String] =
        universe.termNameUnapply(arg)
    }
  }
}
```
In a nutshell,
- the compiler engine API is flat and tried to stay as close as possible to a common   [finally tagless](https://gist.github.com/OlivierBlanvillain/48bb5c66dbb0557da50465809564ee80)  encoding in Scala
- the public macro API stays as close as possible to the shape of the  [Scalameta Tree API](https://github.com/scalameta/scalameta/blob/207e64eed3db6e7f5853a536269a48239717da91/scalameta/trees/shared/src/main/scala/scala/meta/Trees.scala),   and requires only a single `import scala.macros._`

The downsides of this encoding are 
- heavy reliance on casting, each argument from the public API is casted   to the compiler engine API and each return value from the compiler   engine is casted to the public API. To ease maintenance, we can maybe implement a scalafix linter to verify that `Term.Name` is only casted to `TermName`, etc.
- duplication, there is a big parallel between the compiler engine API   and public macro API. In its final form, the API will likely consist   of several hundred methods. On the other hand, we also remove a lot of tricky machinery (`def TermName: TermNameCompanion`, TreeAbstracts, TreeCompanions, TreeExtensions) from the core API.

**Comment by julienrf** [comment]
> ~~~ scala
> private[macros] def universe: Universe = {
>   val result = universeStore.get
>   if (result == null) sys.error("this API can only be called in a macro expansion")
>   else result
> }
> ~~~

Do we even have to provide runtime bytecode for that `macros` package object? I think that, from the point of view of macro authors the `macros` package object should opaquely have type `Universe` but its bytecode should never be part of a Scala program.

In my opinion, having a “public facing” `macros` package object that contains just (lots of) forwarders to the “internal” implementation has the following additional cons:
- adds one layer of indirection
- if it is untyped then it’s going to be a burden to maintain
- if it uses a magical `!` unary operator for type casts then it will be just confusing for readers

I don’t have a deep understanding of macros implementation but it seems that we should make the `macros` term be **synthesized** by the compiler (no `macros/package.scala` source file) and have type `Universe`. That `Universe` type could be defined as follows (similar encoding as the current one):

~~~ scala
// macros/Universe.scala (which happens to also be the “public facing” API)
trait Universe {
  type Tree
  type Term <: Tree
  val Term: TermCompanion
  trait TermCompanion {
    type Name <: Term
    val Name: NameCompanion
    trait NameCompanion {
      def apply(value: String): Term.Name
      def unapply(arg: Any): Option[String]
    }
  }
}

// compiler engine: ScalacUniverse.scala
class ScalacEngine(g: Global) extends Universe {
  type Tree = g.Position
  type Term = g.Position
  object Term extends TermCompanion {
    type Name = g.Ident
    object Name extends NameCompanion {
      def apply(s: String) = g.Ident(s)
      def unapply(a: Any) = …
    }
  }
}
~~~

I haven’t investigated the problem of cyclic references within `Universe` components, but I think it should be doable to find a way to break down `Universe` into non-cyclic components?

BTW, I’m not able to reproduce the IntelliJ issue you mention with `apply` and `unapply`:

![image](https://user-images.githubusercontent.com/332812/31439866-16b86a8c-ae8e-11e7-8206-7f82264d0f56.png)

Maybe I missed something?

**Comment by olafurpg** [comment]
Thank you for your input @julienrf. I still haven't gone through the refactoring because I have similar concerns as yourself with maintainability of casts and unnecessary indirection. Some questions

- How would you expose `Universe` through `import scala.macros._`? I want to keep compiler/language customizations to a minimum.
- How do you add extension methods such as `Tree.pos` with this scheme?

>  term be synthesized by the compiler 

How would this play with existing tooling? Does it need added to the language spec?

> BTW, I’m not able to reproduce the IntelliJ issue you mention with apply and unapply:

The IntellJ problems may have been caused by the fact that `Name` was a def and not a val.

**Comment by julienrf** [comment]
> How would you expose Universe through import scala.macros._? I want to keep compiler/language customizations to a minimum.
> How would this play with existing tooling? Does it need added to the language spec?

I guess yes, we would have to change the language spec. `scala.macros` would be a term synthesized by the compiler and would have type `Universe`. It would conceptually be equivalent to the following definition:

~~~ scala
package scala
package object macros extends Universe
~~~

(Excepted that this definition doesn’t compile since `Universe` has unimplemented members)

So, users would just `import scala.macros._` to use the macros API.

> How do you add extension methods such as Tree.pos with this scheme?

The simplest way would be to use implicit enrichment:

~~~ scala
// macros/Universe.scala
trait Universe {
  type Position
  type Tree
  def treePos(`this`: Tree): Position
  implicit class TreeOps(`this`: Tree) {
    def pos: Position = treePos(`this`)
  }
}
~~~

Another alternative (if we want to avoid the implicit conversion) would be to put an upper bound to the type member `Tree`:

~~~ scala
// macros/Universe.scala
trait Universe {
  type Position
  type Tree <: TreeOps
  trait TreeOps {
    def pos: Position
  }
}

// compiler engine
class ScalacUniverse(g: Global) extends Universe {
  type Position = g.Position
  case class Tree(underlying: g.Position) extends TreeOps {
    def pos = underlying
  }
}
~~~

But, as you can see, from the compiler engine point of view, we would have to wrap our underlying implementation types to mix the `Ops` in it. In practice I have found that putting upper bounds in the interface were sometimes very constraining for implementers (but maybe that was specific to my use case and was related with the conjoint use of higher-kinded types).

> The IntellJ problems may have been caused by the fact that Name was a def and not a val.

Yeah, probably. I think we should use vals here anyway.

**Comment by julienrf** [comment]
A third alternative would be to do the following:

~~~ scala
trait Universe {
  trait Position
  trait Tree {
    def pos: Position
  }
}

class ScalacUniverse(g: Global)  extends Universe{
  case class Position(underlying: g.Position) extends super.Position
  case class Tree(underlying: g.Position) extends super.Tree {
    def pos = underlying
  }
}
~~~

I’m not sure how reliable this is, though (and I think Dotty doesn’t support that anymore). But at least the user facing API is super clean.

**Comment by olafurpg** [comment]
I verified that changing `def` to `val` fixes the IntelliJ problem, reported https://youtrack.jetbrains.com/issue/SCL-12713 We may need defs to support dynamic updates on tree constructors. I feel that imposing only a single set of tree constructors per classloader (?) is not a good idea and may play badly with build tools like sbt that manipulate multiple Scala versions.

I think we should strive for no changes to scala scoping/typing rules, so we should avoid making `scala.macros` too special. `scala.macros.internal.withUniverse` will be special in the sense that the compiler reflectively invokes it, but `scala.macros` is otherwise compiled like any regular Scala package.

One problem with adding the implicit enrichments inside `Universe` is that they are in scope for engine implementations. I've already hit problems with this approach when implementing the scalac/dotc engines. We could separate the enrichment methods into another trait, but then it would hurt explorability of the public macro API when enrichments are defined far away from the type definitions.

I think we should aim for a design that cleanly separates the shape of the public interface (e.g., enrichments/.apply/.unapply) and the core functionality. If we add utilities to the public interface, it should be super easy to review a diff and verify that no changes impact the core APIs of the macro engine.

The best alternative to casting that I've found so far is to drop the single `import scala.macros._` requirement and go back to path dependent types like in `scala.reflect`. However, from what I've heard, this approach has proven to be a big UX problem for macro writers. For any utility method, it's necessary to keep track of the singleton type of the context. For example, consider 

https://github.com/adamw/macwire/blob/9cc9ad8344f2e038b533d77a6527bc0ea23f5522/macros/src/main/scala/com/softwaremill/macwire/internals/TypeCheckUtil.scala#L5

If `TypeCheckUtil` didn't specify `C <: Context`, then `c.type` gets widened to `Context`.

**Comment by julienrf** [comment]
> One problem with adding the implicit enrichments inside Universe is that they are in scope for engine implementations.

Why is that a problem since anyway the actual methods that are forwarded to by the implicit enrichment are also already available for engine implementations?

**Comment by olafurpg** [comment]
- you need to mentally keep track of which methods are forwarders and which are core
- you can introduce infinite recursion if you call a forwarder method it's corresponding core method
