### ISSUE TITLE
Missing updates to dotty-compiler

### ISSUE THREAD

**Issue by olafurpg** [scalacenter/macros#25]
- scala.macros.Universe has moved to scala.macros.core.Universe in #24 
- DottyUniverse should have a Context available to gensym

**Comment by olafurpg** [comment]
Did https://github.com/scalacenter/dotty/pull/4 also add Context to DottyUniverse?

**Comment by liufengyun** [comment]
It's implemented in the following PR:

https://github.com/scalacenter/macros/pull/26

**Comment by olafurpg** [comment]
Fixed in #26 ?
