### ISSUE TITLE
can the README say something about the new project status?

### ISSUE THREAD

**Issue by SethTisue** [scalacenter/macros#37]

**Comment by olafurpg** [comment]
I agree! I was planning to update the readme once the minutes from the last AB meeting are made public.

**Comment by SethTisue** [comment]
hehe, putting it back on me, I see what you're doing there ;-)

I'm a bit late with the minutes because I lost most of a week to the Northeast Scala Symposium, but I haven't forgotten.

**Comment by notmu** [comment]
Hi, was hoping to find more information on this looking at [scalameta](http://scalameta.org/) and some libraries that use it over @ [ThoughtWorks](https://github.com/ThoughtWorksInc) it seems some people are aware of upcoming changes and the new direction of the project but not sure how to go about piecing together what those might be and what the timeline is. Thank you for any guidance.

**Comment by olafurpg** [comment]
Done. This repo is now archived.
